# Copyright Red Hat

apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: "{{ .ServiceAccountName }}"
  namespace: "{{ .Namespace }}"
  labels:
   {{ .RegisteredClusterNameLabel }}: {{ .RegisteredClusterName }}
   {{ .RegisteredClusterNamespaceLabel }}: {{ .RegisteredClusterNamespace }} 
spec:
  workload:
    manifests:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: singapore:gitopsservice
      rules:
      - apiGroups:
        - "*"
        resources:
        - "*"
        verbs:
        - "*"
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: singapore:gitopsservice
      roleRef:
        apiGroup: ""
        kind: ClusterRole
        name: singapore:gitopsservice
      subjects:
      - kind: ServiceAccount
        name: "{{ .ServiceAccountName }}"
        namespace: open-cluster-management-agent-addon